# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-ast
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: debug-statements
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.6"
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "src/", "tests/"]
        additional_dependencies: [".[toml]"]
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.10"
    hooks:
      - id: vulture
        args: ["--min-confidence", "75", "src/", "tests/"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
