# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-ast
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: debug-statements
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
